[Exception][2018-04-27 16:09:37]>>  [检查版本信息-2018_4_27_16_9_7.py]  [HTTPS://ta.2boss.cn/rabbit/v1/version/checkNewVersion] <EXCEPTION>Traceback (most recent call last):
  File "/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/检查版本信息-2018_4_27_16_9_7.py", line 21, in testDemo
    r = requests.post(self.protocol + domian + url, headers=headers, timeout=8)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 306, in prepare
    self.prepare_headers(headers)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 440, in prepare_headers
    check_header_validity(header)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/utils.py", line 872, in check_header_validity
    "bytes, not %s" % (name, value, type(value)))
InvalidHeader: Value for header {appId: 1} must be of type str or bytes, not <type 'int'>

[Exception][2018-04-27 16:09:37]>>  [检查版本信息-2018_4_27_16_9_7.py] :未获取脚本执行状态，脚本执行失败
[Exception][2018-04-28 11:30:33]>>  [实时获取tab标签发现（信息）-2018_4_23_16_14_40.py]  [HTTPS://ta.2boss.cn/rabbit/v1/2bossmoments/count-new] <EXCEPTION>Traceback (most recent call last):
  File "/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/实时获取tab标签发现（信息）-2018_4_23_16_14_40.py", line 22, in testDemo
    r = requests.get(self.protocol + domian  + url,headers=headers, params=param, timeout=8)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 306, in prepare
    self.prepare_headers(headers)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 438, in prepare_headers
    for header in headers.items():
AttributeError: 'unicode' object has no attribute 'items'

[Exception][2018-04-28 11:30:55]>>  [实时获取tab标签发现（信息）-2018_4_23_16_14_40.py]  [HTTPS://ta.2boss.cn/rabbit/v1/2bossmoments/count-new] <EXCEPTION>Traceback (most recent call last):
  File "/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/实时获取tab标签发现（信息）-2018_4_23_16_14_40.py", line 22, in testDemo
    r = requests.get(self.protocol + domian  + url,headers=headers, params=param, timeout=8)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 306, in prepare
    self.prepare_headers(headers)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 438, in prepare_headers
    for header in headers.items():
AttributeError: 'str' object has no attribute 'items'

[Exception][2018-04-28 11:33:31]>>  [实时获取tab标签发现（信息）-2018_4_23_16_14_40.py]  [HTTPS://ta.2boss.cn/rabbit/v1/2bossmoments/count-new] <EXCEPTION>Traceback (most recent call last):
  File "/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/实时获取tab标签发现（信息）-2018_4_23_16_14_40.py", line 22, in testDemo
    r = requests.get(self.protocol + domian  + url,headers=headers, params=param, timeout=8)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 306, in prepare
    self.prepare_headers(headers)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 438, in prepare_headers
    for header in headers.items():
AttributeError: 'str' object has no attribute 'items'

[Exception][2018-04-28 11:34:13]>>  [实时获取tab标签发现（信息）-2018_4_23_16_14_40.py]  [HTTPS://ta.2boss.cn/rabbit/v1/2bossmoments/count-new] <EXCEPTION>Traceback (most recent call last):
  File "/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/实时获取tab标签发现（信息）-2018_4_23_16_14_40.py", line 22, in testDemo
    r = requests.get(self.protocol + domian  + url,headers=headers, params=param, timeout=8)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 306, in prepare
    self.prepare_headers(headers)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 438, in prepare_headers
    for header in headers.items():
AttributeError: 'unicode' object has no attribute 'items'

[Exception][2018-05-02 11:33:03]>>  [实时获取tab标签发现（信息）-2018_5_2_11_25_46.py] :未获取脚本执行状态，脚本执行失败
[Exception][2018-05-02 13:35:19]>>  [检查版本信息-2018_5_2_13_34_18.py]  [HTTPS://ta.2boss.cn/rabbit/v1/version/checkNewVersion] <EXCEPTION>Traceback (most recent call last):
  File "/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/检查版本信息-2018_5_2_13_34_18.py", line 21, in testDemo
    r = requests.post(self.protocol + domian + url, headers=headers, timeout=8)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 306, in prepare
    self.prepare_headers(headers)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 440, in prepare_headers
    check_header_validity(header)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/utils.py", line 872, in check_header_validity
    "bytes, not %s" % (name, value, type(value)))
InvalidHeader: Value for header {appId: 1} must be of type str or bytes, not <type 'int'>

[Exception][2018-05-02 13:35:19]>>  [检查版本信息-2018_5_2_13_34_18.py] :未获取脚本执行状态，脚本执行失败
[Exception][2018-05-02 13:36:16]>>  [检查版本信息-2018_5_2_13_34_18.py]  [HTTPS://ta.2boss.cn/rabbit/v1/version/checkNewVersion] <EXCEPTION>Traceback (most recent call last):
  File "/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/检查版本信息-2018_5_2_13_34_18.py", line 21, in testDemo
    r = requests.post(self.protocol + domian + url, headers=headers, timeout=8)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 306, in prepare
    self.prepare_headers(headers)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 440, in prepare_headers
    check_header_validity(header)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/utils.py", line 872, in check_header_validity
    "bytes, not %s" % (name, value, type(value)))
InvalidHeader: Value for header {appId: 1} must be of type str or bytes, not <type 'int'>

[Exception][2018-05-02 13:36:16]>>  [检查版本信息-2018_5_2_13_34_18.py] :未获取脚本执行状态，脚本执行失败
[Exception][2018-05-02 13:38:37]>>  [检查版本信息-2018_5_2_13_34_18.py]  [HTTPS://ta.2boss.cn/rabbit/v1/version/checkNewVersion] <EXCEPTION>Traceback (most recent call last):
  File "/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/检查版本信息-2018_5_2_13_34_18.py", line 21, in testDemo
    r = requests.post(self.protocol + domian + url, headers=headers, timeout=8)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 306, in prepare
    self.prepare_headers(headers)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 440, in prepare_headers
    check_header_validity(header)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/utils.py", line 872, in check_header_validity
    "bytes, not %s" % (name, value, type(value)))
InvalidHeader: Value for header {appId: 1} must be of type str or bytes, not <type 'int'>

[Exception][2018-05-02 13:38:37]>>  [检查版本信息-2018_5_2_13_34_18.py] :未获取脚本执行状态，脚本执行失败
[Exception][2018-05-03 15:24:18]>>  [实时获取tab标签发现（信息）-2018_5_3_15_23_36.py]  [HTTPS://ta.2boss.cn/rabbit/v1/2bossmoments/count-new] <EXCEPTION>Traceback (most recent call last):
  File "/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/实时获取tab标签发现（信息）-2018_5_3_15_23_36.py", line 24, in testDemo
    r = requests.get(self.protocol + domian  + url,headers=headers, params=param, timeout=8)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 306, in prepare
    self.prepare_headers(headers)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 440, in prepare_headers
    check_header_validity(header)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/utils.py", line 872, in check_header_validity
    "bytes, not %s" % (name, value, type(value)))
InvalidHeader: Value for header {a: 123} must be of type str or bytes, not <type 'int'>

[Exception][2018-05-03 15:24:18]>>  [实时获取tab标签发现（信息）-2018_5_3_15_23_36.py] :未获取脚本执行状态，脚本执行失败
[Exception][2018-05-03 15:24:19]>>  [检查版本信息-2018_5_3_15_23_36.py]  [HTTPS://ta.2boss.cn/rabbit/v1/version/checkNewVersion] <EXCEPTION>Traceback (most recent call last):
  File "/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/检查版本信息-2018_5_3_15_23_36.py", line 21, in testDemo
    r = requests.post(self.protocol + domian + url, headers=headers, timeout=8)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 306, in prepare
    self.prepare_headers(headers)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 440, in prepare_headers
    check_header_validity(header)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/utils.py", line 872, in check_header_validity
    "bytes, not %s" % (name, value, type(value)))
InvalidHeader: Value for header {appId: 1} must be of type str or bytes, not <type 'int'>

[Exception][2018-05-03 15:24:19]>>  [检查版本信息-2018_5_3_15_23_36.py] :未获取脚本执行状态，脚本执行失败
[Exception][2018-05-04 09:47:45]>>  [更新绑定用户信息1-2018_5_3_17_48_59.py]  [HTTPS://ta.2boss.cn/rabbit/v1/im/imUpdateCustomer] <EXCEPTION>Traceback (most recent call last):
  File "/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/更新绑定用户信息1-2018_5_3_17_48_59.py", line 25, in testDemo
    print param.urlparse()
AttributeError: 'str' object has no attribute 'urlparse'

[Exception][2018-05-04 09:57:36]>>  [更新绑定用户信息1-2018_5_3_17_48_59.py]  [HTTPS://ta.2boss.cn/rabbit/v1/im/imUpdateCustomer] <EXCEPTION>Traceback (most recent call last):
  File "/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/更新绑定用户信息1-2018_5_3_17_48_59.py", line 26, in testDemo
    print urllib.parse(param)
AttributeError: 'module' object has no attribute 'parse'

