[Exception][2018-04-02 18:15:57]>>  [/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/平台框架获取事件列表-2018_4_2_15_57_3.py][HTTPS://ta1.2boss.cn/rabbit/v1/event/getEventList]:[requests.exceptions.ConnectionError]
[Exception][2018-04-02 18:15:58]>>  [平台框架获取事件列表-2018_4_2_15_57_3.py] :未获取脚本执行状态，脚本执行失败list index out of range
[Exception][2018-04-02 18:16:13]>>  [/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/更新绑定用户信息-2018_4_2_15_57_3.py][HTTPS://ta1.2boss.cn/superior/v1/im/imUpdateCustomer]:[requests.exceptions.ConnectionError]
[Exception][2018-04-02 18:16:14]>>  [更新绑定用户信息-2018_4_2_15_57_3.py] :未获取脚本执行状态，脚本执行失败list index out of range
[Exception][2018-04-03 13:59:49]>>  [/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/平台框架获取事件列表-2018_4_2_15_57_3.py][HTTPS://ta1.2boss.cn/rabbit/v1/event/getEventList]:[requests.exceptions.ConnectionError]
[Exception][2018-04-03 13:59:49]>>  [平台框架获取事件列表-2018_4_2_15_57_3.py] :未获取脚本执行状态，脚本执行失败list index out of range
[Exception][2018-04-03 14:00:06]>>  [/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/更新绑定用户信息-2018_4_2_15_57_3.py][HTTPS://ta1.2boss.cn/superior/v1/im/imUpdateCustomer]:[requests.exceptions.ConnectionError]
[Exception][2018-04-03 14:00:07]>>  [更新绑定用户信息-2018_4_2_15_57_3.py] :未获取脚本执行状态，脚本执行失败list index out of range
[Exception][2018-04-10 15:17:31]>>  [/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/存储用户Session-2018_4_2_15_57_3.py][HTTPS://ta1.2boss.cn/ubt/api/session]:[requests.exceptions.ConnectionError]
[Exception][2018-04-10 15:17:31]>>  [存储用户Session-2018_4_2_15_57_3.py] :未获取脚本执行状态，脚本执行失败list index out of range
[Exception][2018-04-10 15:17:49]>>  [/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/更新绑定用户信息-2018_4_2_15_57_3.py][HTTPS://1ta.2boss.cn/superior/v1/im/imUpdateCustomer]:[requests.exceptions.ConnectionError]
[Exception][2018-04-10 15:17:49]>>  [更新绑定用户信息-2018_4_2_15_57_3.py] :未获取脚本执行状态，脚本执行失败list index out of range
[Exception][2018-04-10 15:20:15]>>  [/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/更新绑定用户信息-2018_4_2_15_57_3.py][HTTPS://1ta.2boss.cn/superior/v1/im/imUpdateCustomer]:[requests.exceptions.ConnectionError]
[Exception][2018-04-10 16:23:31]>>  [/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/存储用户Session-2018_4_2_15_57_3.py][HTTPS://ta1.2boss.cn/ubt/api/session]:[requests.exceptions.ConnectionError]
[Exception][2018-04-10 16:23:31]>>  [存储用户Session-2018_4_2_15_57_3.py] :未获取脚本执行状态，脚本执行失败list index out of range
[Exception][2018-04-10 16:24:40]>>  [/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/存储用户Session-2018_4_2_15_57_3.py][HTTPS://ta1.2boss.cn/ubt/api/session]:[requests.exceptions.ConnectionError]
[Exception][2018-04-10 16:24:40]>>  [存储用户Session-2018_4_2_15_57_3.py] :未获取脚本执行状态，脚本执行失败list index out of range
[Exception][2018-04-10 16:38:09]>>  [/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/存储用户Session-2018_4_2_15_57_3.py][HTTPS://ta1.2boss.cn/ubt/api/session]:[requests.exceptions.ConnectionError]
[Exception][2018-04-10 16:38:10]>>  [存储用户Session-2018_4_2_15_57_3.py] :未获取脚本执行状态，脚本执行失败list index out of range
[Exception][2018-04-10 16:40:29]>>  [/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/存储用户Session-2018_4_2_15_57_3.py][HTTPS://ta1.2boss.cn/ubt/api/session]:[requests.exceptions.ConnectionError]
[Exception][2018-04-10 16:40:30]>>  [存储用户Session-2018_4_2_15_57_3.py] :未获取脚本执行状态，脚本执行失败list index out of range
[Exception][2018-04-10 20:54:03]>>  [/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/存储用户Session-2018_4_2_15_57_3.py][HTTPS://ta1.2boss.cn/ubt/api/session]:[requests.exceptions.ConnectionError]
[Exception][2018-04-10 20:54:03]>>  [存储用户Session-2018_4_2_15_57_3.py] :未获取脚本执行状态，脚本执行失败list index out of range
[Exception][2018-04-10 20:55:36]>>  [/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/存储用户Session-2018_4_2_15_57_3.py][HTTPS://ta1.2boss.cn/ubt/api/session]:[requests.exceptions.ConnectionError]
[Exception][2018-04-10 20:55:37]>>  [存储用户Session-2018_4_2_15_57_3.py] :未获取脚本执行状态，脚本执行失败list index out of range
[Exception][2018-04-10 21:00:35]>>  [/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/存储用户Session-2018_4_2_15_57_3.py][HTTPS://ta1.2boss.cn/ubt/api/session]:[requests.exceptions.ConnectionError]
[Exception][2018-04-10 21:00:36]>>  [存储用户Session-2018_4_2_15_57_3.py] :未获取脚本执行状态，脚本执行失败list index out of range
[Exception][2018-04-10 21:02:30]>>  [/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/存储用户Session-2018_4_2_15_57_3.py][HTTPS://ta1.2boss.cn/ubt/api/session]:[requests.exceptions.ConnectionError]
[Exception][2018-04-10 21:02:31]>>  [存储用户Session-2018_4_2_15_57_3.py] :未获取脚本执行状态，脚本执行失败list index out of range
[Exception][2018-04-10 21:08:59]>>  [/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/存储用户Session-2018_4_2_15_57_3.py][HTTPS://ta1.2boss.cn/ubt/api/session]:[requests.exceptions.ConnectionError]
[Exception][2018-04-10 21:09:00]>>  [存储用户Session-2018_4_2_15_57_3.py] :未获取脚本执行状态，脚本执行失败list index out of range
[Exception][2018-04-10 21:38:58]>>  [/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/登录初始化-2018_4_2_15_57_3.py][HTTPS://ta1.2boss.cn/resource/api/init]:[requests.exceptions.ConnectionError]
[Exception][2018-04-10 21:38:59]>>  [登录初始化-2018_4_2_15_57_3.py] :未获取脚本执行状态，脚本执行失败list index out of range
