INFO 2018-04-19 14:18:40,841 views.py views login_handle 56: 请输入正确的用户名和密码！
INFO 2018-04-19 14:18:50,140 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-19 14:22:43,932 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-19 14:27:10,751 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-19 14:35:18,838 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-19 14:46:02,971 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-19 15:06:35,567 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-19 15:09:25,360 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-19 15:13:22,409 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-19 15:16:06,003 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-19 15:32:17,463 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-19 16:01:23,965 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-19 16:05:31,894 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-19 16:08:50,010 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-19 16:20:58,137 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-19 16:29:08,737 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-19 17:54:31,945 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-19 17:55:12,977 views.py views login_handle 53: [liud] 登录成功
INFO 2018-04-19 17:58:26,764 views.py views project_manage 87: 进入项目中心-->项目管理页面
INFO 2018-04-19 17:58:26,816 views.py views project_manage 87: 进入项目中心-->项目管理页面
INFO 2018-04-19 17:58:27,005 views.py views Read_all_project 106: 查询所有项目
INFO 2018-04-19 17:58:27,138 views.py views Read_all_project 106: 查询所有项目
INFO 2018-04-19 18:01:16,411 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-19 18:15:59,389 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-20 09:09:30,302 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-20 09:10:09,232 views.py views login_handle 53: [luoyh] 登录成功
INFO 2018-04-20 09:10:29,918 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-20 09:33:46,847 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-20 09:36:11,053 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-20 09:36:51,717 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-20 09:37:29,230 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-20 09:38:33,675 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-20 09:39:14,085 views.py views login_handle 53: [gonglp] 登录成功
ERROR 2018-04-20 09:45:56,384 views.py views execute_test_script 1282: 存储用户Session-2018_4_13_11_19_52.py:FAILED: error message [ 未获取脚本执行状态，脚本执行失败 ] Traceback (most recent call last):
  File "/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/存储用户Session-2018_4_13_11_19_52.py", line 19, in testDemo
    r = requests.put(self.protocol + domian + url, json=param, timeout=8)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 126, in put
    return request('put', url, data=data, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='ta1.2boss.cn', port=443): Max retries exceeded with url: /ubt/api/session (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36e461bb50>: Failed to establish a new connection: [Errno -5] No address associated with hostname',))


INFO 2018-04-20 09:45:57,441 views.py views execute_test_script 1244: 实时获取tab标签发现（信息）-2018_4_13_11_19_52.py:PASS:[time_consuming:0.346089]{ response : 'resultCode: 0' }
ERROR 2018-04-20 09:45:57,835 views.py views execute_test_script 1282: 平台框架获取事件列表-2018_4_13_11_19_52.py:FAILED: error message [ 未获取脚本执行状态，脚本执行失败 ] Traceback (most recent call last):
  File "/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/平台框架获取事件列表-2018_4_13_11_19_52.py", line 21, in testDemo
    r = requests.get(self.protocol + domian  + url,headers=headers, params=param, timeout=8)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 306, in prepare
    self.prepare_headers(headers)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 438, in prepare_headers
    for header in headers.items():
AttributeError: 'str' object has no attribute 'items'


INFO 2018-04-20 09:53:30,821 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-20 09:54:50,174 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-20 09:56:40,178 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-20 10:17:38,867 views.py views login_handle 53: [gonglp] 登录成功
ERROR 2018-04-20 10:18:34,839 views.py views execute_test_script 1283: 存储用户Session-2018_4_13_11_19_52.py:FAILED: error message [ 未获取脚本执行状态，脚本执行失败 ] Traceback (most recent call last):
  File "/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/存储用户Session-2018_4_13_11_19_52.py", line 19, in testDemo
    r = requests.put(self.protocol + domian + url, json=param, timeout=8)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 126, in put
    return request('put', url, data=data, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='ta1.2boss.cn', port=443): Max retries exceeded with url: /ubt/api/session (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fcfcf1ddb50>: Failed to establish a new connection: [Errno -5] No address associated with hostname',))


INFO 2018-04-20 10:18:36,082 views.py views execute_test_script 1245: 实时获取tab标签发现（信息）-2018_4_13_11_19_52.py:PASS:[time_consuming:0.43436]{ response : 'resultCode: 0' }
ERROR 2018-04-20 10:18:36,506 views.py views execute_test_script 1283: 平台框架获取事件列表-2018_4_13_11_19_52.py:FAILED: error message [ 未获取脚本执行状态，脚本执行失败 ] Traceback (most recent call last):
  File "/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/平台框架获取事件列表-2018_4_13_11_19_52.py", line 21, in testDemo
    r = requests.get(self.protocol + domian  + url,headers=headers, params=param, timeout=8)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 306, in prepare
    self.prepare_headers(headers)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 438, in prepare_headers
    for header in headers.items():
AttributeError: 'str' object has no attribute 'items'


INFO 2018-04-20 10:20:24,978 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-20 10:33:09,031 views.py views login_handle 53: [lerj] 登录成功
ERROR 2018-04-20 10:33:46,593 views.py views execute_test_script 1258: 更新绑定用户信息-2018_4_13_11_19_52.py:FAILED: error message [', "{u'status': 404, u'timestamp': 1524191626469, u'message': u'No message available', u'path': u'/superior/v1/im/imUpdateCustomer12', u'error': u'Not Found'}")
]
ERROR 2018-04-20 10:33:47,159 views.py views execute_test_script 1283: 检查版本信息-2018_4_13_11_19_52.py:FAILED: error message [ 未获取脚本执行状态，脚本执行失败 ] Traceback (most recent call last):
  File "/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/检查版本信息-2018_4_13_11_19_52.py", line 17, in testDemo
    r = requests.post(self.protocol + domian + url, headers=headers, timeout=8)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 306, in prepare
    self.prepare_headers(headers)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 440, in prepare_headers
    check_header_validity(header)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/utils.py", line 872, in check_header_validity
    "bytes, not %s" % (name, value, type(value)))
InvalidHeader: Value for header {appId: 1} must be of type str or bytes, not <type 'int'>


INFO 2018-04-20 10:33:47,822 views.py views execute_test_script 1245: 登录初始化-2018_4_13_11_19_52.py:PASS:[time_consuming:0.205222]{ response : 'resultCode: 0' }
ERROR 2018-04-20 10:44:12,706 views.py views execute_test_script 1258: 更新绑定用户信息-2018_4_13_11_19_52.py:FAILED: error message [', "{u'status': 404, u'timestamp': 1524192252606, u'message': u'No message available', u'path': u'/superior/v1/im/imUpdateCustomer12', u'error': u'Not Found'}")
]
ERROR 2018-04-20 10:44:52,120 views.py views execute_test_script 1258: 更新绑定用户信息-2018_4_13_11_19_52.py:FAILED: error message [', "{u'status': 404, u'timestamp': 1524192292021, u'message': u'No message available', u'path': u'/superior/v1/im/imUpdateCustomer12', u'error': u'Not Found'}")
]
INFO 2018-04-20 10:45:34,020 views.py views login_handle 53: [lerj] 登录成功
INFO 2018-04-20 10:45:50,057 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-20 10:46:02,268 views.py views login_handle 53: [lerj] 登录成功
ERROR 2018-04-20 10:46:33,593 views.py views execute_test_script 1258: 更新绑定用户信息-2018_4_13_11_19_52.py:FAILED: error message [', "{u'status': 404, u'timestamp': 1524192393496, u'message': u'No message available', u'path': u'/superior/v1/im/imUpdateCustomer12', u'error': u'Not Found'}")
]
ERROR 2018-04-20 10:48:13,842 views.py views execute_test_script 1258: 更新绑定用户信息-2018_4_13_11_19_52.py:FAILED: error message [', "{u'status': 404, u'timestamp': 1524192493743, u'message': u'No message available', u'path': u'/superior/v1/im/imUpdateCustomer12', u'error': u'Not Found'}")
]
INFO 2018-04-20 11:21:21,644 views.py views login_handle 53: [lerj] 登录成功
ERROR 2018-04-20 11:21:57,605 views.py views execute_test_script 1258: 更新绑定用户信息-2018_4_13_11_19_52.py:FAILED: error message [', "{u'status': 404, u'timestamp': 1524194517404, u'message': u'No message available', u'path': u'/superior/v1/im/imUpdateCustomer12', u'error': u'Not Found'}")
]
ERROR 2018-04-20 11:26:50,255 views.py views execute_test_script 1258: 更新绑定用户信息-2018_4_13_11_19_52.py:FAILED: error message [', "{u'status': 404, u'timestamp': 1524194809923, u'message': u'No message available', u'path': u'/superior/v1/im/imUpdateCustomer12', u'error': u'Not Found'}")
]
INFO 2018-04-20 11:29:29,360 views.py views login_handle 53: [lerj] 登录成功
ERROR 2018-04-20 11:30:04,652 views.py views execute_test_script 1283: 检查版本信息-2018_4_13_11_19_52.py:FAILED: error message [ 未获取脚本执行状态，脚本执行失败 ] Traceback (most recent call last):
  File "/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/检查版本信息-2018_4_13_11_19_52.py", line 17, in testDemo
    r = requests.post(self.protocol + domian + url, headers=headers, timeout=8)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 306, in prepare
    self.prepare_headers(headers)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 440, in prepare_headers
    check_header_validity(header)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/utils.py", line 872, in check_header_validity
    "bytes, not %s" % (name, value, type(value)))
InvalidHeader: Value for header {appId: 1} must be of type str or bytes, not <type 'int'>


INFO 2018-04-20 11:39:45,802 views.py views login_handle 53: [lerj] 登录成功
ERROR 2018-04-20 11:40:19,102 views.py views execute_test_script 1277: 检查版本信息-2018_4_13_11_19_52.py:FAILED: error message [ 未获取脚本执行状态，脚本执行失败 ] Traceback (most recent call last):
  File "/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/检查版本信息-2018_4_13_11_19_52.py", line 17, in testDemo
    r = requests.post(self.protocol + domian + url, headers=headers, timeout=8)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 306, in prepare
    self.prepare_headers(headers)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 440, in prepare_headers
    check_header_validity(header)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/utils.py", line 872, in check_header_validity
    "bytes, not %s" % (name, value, type(value)))
InvalidHeader: Value for header {appId: 1} must be of type str or bytes, not <type 'int'>


ERROR 2018-04-20 11:41:22,545 views.py views execute_test_script 1277: 检查版本信息-2018_4_13_11_19_52.py:FAILED: error message [ 未获取脚本执行状态，脚本执行失败 ] Traceback (most recent call last):
  File "/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/检查版本信息-2018_4_13_11_19_52.py", line 17, in testDemo
    r = requests.post(self.protocol + domian + url, headers=headers, timeout=8)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 306, in prepare
    self.prepare_headers(headers)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 440, in prepare_headers
    check_header_validity(header)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/utils.py", line 872, in check_header_validity
    "bytes, not %s" % (name, value, type(value)))
InvalidHeader: Value for header {appId: 1} must be of type str or bytes, not <type 'int'>


INFO 2018-04-20 13:28:36,509 views.py views project_manage 87: 进入项目中心-->项目管理页面
INFO 2018-04-20 13:28:36,560 views.py views project_manage 87: 进入项目中心-->项目管理页面
INFO 2018-04-20 13:28:36,757 views.py views Read_all_project 106: 查询所有项目
INFO 2018-04-20 13:28:36,867 views.py views Read_all_project 106: 查询所有项目
INFO 2018-04-20 13:28:39,030 views.py views income_project 142: lerj进入项目[20171021]
INFO 2018-04-20 13:29:05,277 views.py views project_manage 87: 进入项目中心-->项目管理页面
INFO 2018-04-20 13:29:05,375 views.py views Read_all_project 106: 查询所有项目
INFO 2018-04-20 13:29:16,922 views.py views project_manage 87: 进入项目中心-->项目管理页面
INFO 2018-04-20 13:29:16,935 views.py views project_manage 87: 进入项目中心-->项目管理页面
INFO 2018-04-20 13:29:17,043 views.py views Read_all_project 106: 查询所有项目
INFO 2018-04-20 13:29:17,198 views.py views Read_all_project 106: 查询所有项目
INFO 2018-04-20 13:29:36,989 views.py views income_project 142: lerj进入项目[20171022]
INFO 2018-04-20 13:29:41,876 views.py views project_manage 87: 进入项目中心-->项目管理页面
INFO 2018-04-20 13:29:41,970 views.py views Read_all_project 106: 查询所有项目
INFO 2018-04-20 13:29:58,359 views.py views project_manage 87: 进入项目中心-->项目管理页面
INFO 2018-04-20 13:29:58,368 views.py views project_manage 87: 进入项目中心-->项目管理页面
INFO 2018-04-20 13:29:58,483 views.py views Read_all_project 106: 查询所有项目
INFO 2018-04-20 13:29:58,635 views.py views Read_all_project 106: 查询所有项目
INFO 2018-04-20 13:30:04,523 views.py views income_project 142: lerj进入项目[TBS_USER_20180328]
INFO 2018-04-20 13:30:13,250 views.py views workon_tabs_api 386: lerj进入接口管理页面 [TBS_USER_20180328]
INFO 2018-04-20 13:30:15,196 views.py views income_project 142: 进入项目[TBS_USER_20180328]
INFO 2018-04-20 13:30:25,686 views.py views project_manage 87: 进入项目中心-->项目管理页面
INFO 2018-04-20 13:30:25,694 views.py views project_manage 87: 进入项目中心-->项目管理页面
INFO 2018-04-20 13:30:25,826 views.py views Read_all_project 106: 查询所有项目
INFO 2018-04-20 13:30:32,645 views.py views income_project 142: lerj进入项目[TBS_USER_20180328]
INFO 2018-04-20 13:30:36,570 views.py views workon_tabs_api 386: lerj进入接口管理页面 [TBS_USER_20180328]
INFO 2018-04-20 13:42:41,774 views.py views login_handle 53: [lerj] 登录成功
INFO 2018-04-20 13:43:00,290 views.py views login_handle 53: [lerj] 登录成功
INFO 2018-04-20 13:43:14,259 views.py views login_handle 53: [lerj] 登录成功
INFO 2018-04-20 13:43:36,524 views.py views login_handle 53: [lerj] 登录成功
INFO 2018-04-20 13:46:40,482 views.py views login_handle 53: [lerj] 登录成功
INFO 2018-04-20 13:48:52,551 views.py views login_handle 53: [lerj] 登录成功
INFO 2018-04-20 13:54:12,573 views.py views login_handle 53: [lerj] 登录成功
INFO 2018-04-20 13:54:23,983 views.py views project_manage 87: 进入项目中心-->项目管理页面
INFO 2018-04-20 13:54:23,991 views.py views project_manage 87: 进入项目中心-->项目管理页面
INFO 2018-04-20 13:54:24,520 views.py views Read_all_project 106: 查询所有项目
INFO 2018-04-20 13:57:06,146 views.py views login_handle 53: [lerj] 登录成功
INFO 2018-04-20 14:00:03,851 views.py views login_handle 53: [lerj] 登录成功
ERROR 2018-04-20 14:01:37,615 views.py views execute_test_script 1277: 检查版本信息-2018_4_13_11_19_52.py:FAILED: error message [ 未获取脚本执行状态，脚本执行失败 ] Traceback (most recent call last):
  File "/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/检查版本信息-2018_4_13_11_19_52.py", line 17, in testDemo
    r = requests.post(self.protocol + domian + url, headers=headers, timeout=8)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 306, in prepare
    self.prepare_headers(headers)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 440, in prepare_headers
    check_header_validity(header)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/utils.py", line 872, in check_header_validity
    "bytes, not %s" % (name, value, type(value)))
InvalidHeader: Value for header {appId: 1} must be of type str or bytes, not <type 'int'>


INFO 2018-04-20 14:04:50,019 views.py views execute_test_script 1245: 登录初始化-2018_4_13_11_19_52.py:PASS:[time_consuming:0.20471]{ response : 'resultCode: 0' }
INFO 2018-04-20 14:10:38,304 views.py views execute_test_script 1245: 登录初始化-2018_4_13_11_19_52.py:PASS:[time_consuming:0.163238]{ response : 'resultCode: 0' }
INFO 2018-04-20 14:13:31,457 views.py views login_handle 53: [lerj] 登录成功
INFO 2018-04-20 14:13:51,406 views.py views execute_test_script 1245: 登录初始化-2018_4_13_11_19_52.py:PASS:[time_consuming:0.123816]{ response : 'resultCode: 0' }
INFO 2018-04-20 14:16:50,559 views.py views login_handle 53: [lerj] 登录成功
INFO 2018-04-20 14:17:18,112 views.py views execute_test_script 1245: 登录初始化-2018_4_13_11_19_52.py:PASS:[time_consuming:0.0686]{ response : 'resultCode: 0' }
INFO 2018-04-20 14:21:22,558 views.py views execute_test_script 1245: 实时获取tab标签发现（信息）-2018_4_13_11_19_52.py:PASS:[time_consuming:0.414741]{ response : 'resultCode: 0' }
ERROR 2018-04-20 14:21:23,576 views.py views execute_test_script 1277: 平台框架获取事件列表-2018_4_13_11_19_52.py:FAILED: error message [ 未获取脚本执行状态，脚本执行失败 ] Traceback (most recent call last):
  File "/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/平台框架获取事件列表-2018_4_13_11_19_52.py", line 21, in testDemo
    r = requests.get(self.protocol + domian  + url,headers=headers, params=param, timeout=8)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 306, in prepare
    self.prepare_headers(headers)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 438, in prepare_headers
    for header in headers.items():
AttributeError: 'str' object has no attribute 'items'


INFO 2018-04-20 14:24:18,554 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-20 14:24:36,218 views.py views execute_test_script 1245: 实时获取tab标签发现（信息）-2018_4_13_11_19_52.py:PASS:[time_consuming:0.377444]{ response : 'resultCode: 0' }
ERROR 2018-04-20 14:24:37,725 views.py views execute_test_script 1277: 平台框架获取事件列表-2018_4_13_11_19_52.py:FAILED: error message [ 未获取脚本执行状态，脚本执行失败 ] Traceback (most recent call last):
  File "/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/平台框架获取事件列表-2018_4_13_11_19_52.py", line 21, in testDemo
    r = requests.get(self.protocol + domian  + url,headers=headers, params=param, timeout=8)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 306, in prepare
    self.prepare_headers(headers)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 438, in prepare_headers
    for header in headers.items():
AttributeError: 'str' object has no attribute 'items'


INFO 2018-04-20 14:26:42,260 views.py views execute_test_script 1245: 实时获取tab标签发现（信息）-2018_4_13_11_19_52.py:PASS:[time_consuming:0.346707]{ response : 'resultCode: 0' }
ERROR 2018-04-20 14:26:42,847 views.py views execute_test_script 1277: 平台框架获取事件列表-2018_4_13_11_19_52.py:FAILED: error message [ 未获取脚本执行状态，脚本执行失败 ] Traceback (most recent call last):
  File "/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/平台框架获取事件列表-2018_4_13_11_19_52.py", line 21, in testDemo
    r = requests.get(self.protocol + domian  + url,headers=headers, params=param, timeout=8)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 306, in prepare
    self.prepare_headers(headers)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 438, in prepare_headers
    for header in headers.items():
AttributeError: 'str' object has no attribute 'items'


INFO 2018-04-20 14:32:42,621 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-20 14:32:57,624 views.py views execute_test_script 1245: 登录初始化-2018_4_13_11_19_52.py:PASS:[time_consuming:0.096532]{ response : 'resultCode: 0' }
INFO 2018-04-20 15:06:29,852 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-20 15:08:13,981 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-20 15:09:35,826 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-20 15:11:45,081 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-20 15:15:55,036 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-20 15:45:10,566 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-20 16:23:27,170 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-20 16:26:09,662 views.py views login_handle 56: 请输入正确的用户名和密码！
INFO 2018-04-20 16:26:18,132 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-20 18:13:00,839 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-20 18:23:22,796 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-20 18:35:27,850 views.py views execute_test_script 1245: 存储用户Session-2018_4_20_18_23_32.py:PASS:[time_consuming:0.139682]{ response : 'resultCode: 0' }
INFO 2018-04-20 18:35:28,540 views.py views execute_test_script 1245: 实时获取tab标签发现（信息）-2018_4_20_18_23_32.py:PASS:[time_consuming:0.20159]{ response : 'resultCode: 0' }
INFO 2018-04-20 18:35:28,885 views.py views execute_test_script 1245: 平台框架获取事件列表-2018_4_20_18_23_32.py:PASS:[time_consuming:0.059206]{ response : 'resultCode: 0' }
INFO 2018-04-20 18:35:29,198 views.py views execute_test_script 1245: 更新绑定用户信息-2018_4_20_18_23_32.py:PASS:[time_consuming:0.073159]{ response : 'resultCode: 0' }
ERROR 2018-04-20 18:35:29,474 views.py views execute_test_script 1277: 检查版本信息-2018_4_20_18_23_31.py:FAILED: error message [ 未获取脚本执行状态，脚本执行失败 ] Traceback (most recent call last):
  File "/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/检查版本信息-2018_4_20_18_23_31.py", line 17, in testDemo
    r = requests.post(self.protocol + domian + url, headers=headers, timeout=8)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 306, in prepare
    self.prepare_headers(headers)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 440, in prepare_headers
    check_header_validity(header)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/utils.py", line 872, in check_header_validity
    "bytes, not %s" % (name, value, type(value)))
InvalidHeader: Value for header {appId: 1} must be of type str or bytes, not <type 'int'>


INFO 2018-04-20 18:35:29,769 views.py views execute_test_script 1245: 登录初始化-2018_4_20_18_23_32.py:PASS:[time_consuming:0.053972]{ response : 'resultCode: 0' }
INFO 2018-04-23 10:29:27,982 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-23 11:00:27,156 views.py views project_manage 87: 进入项目中心-->项目管理页面
INFO 2018-04-23 11:00:27,245 views.py views project_manage 87: 进入项目中心-->项目管理页面
INFO 2018-04-23 11:00:27,484 views.py views Read_all_project 106: 查询所有项目
INFO 2018-04-23 11:00:27,776 views.py views Read_all_project 106: 查询所有项目
INFO 2018-04-23 11:00:29,921 views.py views income_project 142: gonglp进入项目[TBS_USER_20180328]
INFO 2018-04-23 11:00:32,166 views.py views workon_tabs_api 386: gonglp进入接口管理页面 [TBS_USER_20180328]
INFO 2018-04-23 13:15:45,164 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-23 13:15:56,453 views.py views execute_maoyan_script 1605: 冒烟测色执行失败 [Caused by :兔博士用户端 还有冒烟用例未生成测试脚本，请补充测试脚本！]
INFO 2018-04-23 13:17:21,127 views.py views execute_maoyan_script 1605: 冒烟测色执行失败 [Caused by :兔博士用户端 还有冒烟用例未生成测试脚本，请补充测试脚本！]
INFO 2018-04-23 13:17:26,644 views.py views execute_maoyan_script 1605: 冒烟测色执行失败 [Caused by :兔博士用户端 还有冒烟用例未生成测试脚本，请补充测试脚本！]
INFO 2018-04-23 13:19:40,115 views.py views execute_maoyan_script 1605: 冒烟测色执行失败 [Caused by :兔博士用户端 还有冒烟用例未生成测试脚本，请补充测试脚本！][u'TBS_ZF_RecordUserAccess', u'TBS_ZF_Session']
INFO 2018-04-23 13:37:41,217 views.py views execute_maoyan_script 1605: 冒烟测色执行失败 [Caused by :兔博士用户端 还有冒烟用例未生成测试脚本，请补充测试脚本！] 请检查以下case_id [u'TBS_ZF_RecordUserAccess', u'TBS_ZF_Session']
INFO 2018-04-23 13:39:52,353 views.py views execute_maoyan_script 1605: 冒烟测色执行失败 [Caused by :兔博士用户端 还有冒烟用例未生成测试脚本，请补充测试脚本！] 请检查以下case_id [u'TBS_ZF_Session']
INFO 2018-04-23 13:42:02,384 views.py views project_manage 87: 进入项目中心-->项目管理页面
INFO 2018-04-23 13:42:02,414 views.py views project_manage 87: 进入项目中心-->项目管理页面
INFO 2018-04-23 13:42:02,561 views.py views Read_all_project 106: 查询所有项目
INFO 2018-04-23 13:42:02,750 views.py views Read_all_project 106: 查询所有项目
INFO 2018-04-23 13:42:06,691 views.py views income_project 142: gonglp进入项目[TBS_USER_20180328]
INFO 2018-04-23 13:42:08,670 views.py views workon_tabs_api 386: gonglp进入接口管理页面 [TBS_USER_20180328]
INFO 2018-04-23 14:37:25,554 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-23 14:49:26,886 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-23 14:49:40,979 views.py views execute_script_result_analysis_fun 1607: 登录初始化:PASS:[time_consuming:0.120489]{ response : 'resultCode: 0' }
INFO 2018-04-23 14:52:38,243 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-23 14:53:31,971 views.py views execute_script_result_analysis_fun 1607: 登录初始化:PASS:[time_consuming:0.056293]{ response : 'resultCode: 0' }
INFO 2018-04-23 14:53:33,739 views.py views execute_script_result_analysis_fun 1607: 首页(顶部区域搜索框点击):PASS:[time_consuming:0.063808]{ response : 'resultCode: 0' }
INFO 2018-04-23 14:53:35,276 views.py views execute_script_result_analysis_fun 1607: 存储用户Session:PASS:[time_consuming:0.051287]{ response : 'resultCode: 0' }
INFO 2018-04-23 14:59:06,140 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-23 14:59:32,564 views.py views execute_script_result_analysis_fun 1607: 登录初始化:PASS:[time_consuming:0.108857]{ response : 'resultCode: 0' }
INFO 2018-04-23 14:59:32,928 views.py views execute_script_result_analysis_fun 1607: 首页(顶部区域搜索框点击):PASS:[time_consuming:0.067982]{ response : 'resultCode: 0' }
INFO 2018-04-23 14:59:33,226 views.py views execute_script_result_analysis_fun 1607: 存储用户Session:PASS:[time_consuming:0.054293]{ response : 'resultCode: 0' }
INFO 2018-04-23 15:01:50,487 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-23 15:02:03,767 views.py views execute_script_result_analysis_fun 1607: 登录初始化:PASS:[time_consuming:0.115363]{ response : 'resultCode: 0' }
INFO 2018-04-23 15:02:04,608 views.py views execute_script_result_analysis_fun 1607: 首页(顶部区域搜索框点击):PASS:[time_consuming:0.065793]{ response : 'resultCode: 0' }
INFO 2018-04-23 15:02:04,922 views.py views execute_script_result_analysis_fun 1607: 存储用户Session:PASS:[time_consuming:0.054428]{ response : 'resultCode: 0' }
INFO 2018-04-23 15:07:06,649 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-23 15:07:43,920 views.py views execute_script_result_analysis_fun 1607: 登录初始化:PASS:[time_consuming:0.06816]{ response : 'resultCode: 0' }
INFO 2018-04-23 15:07:44,367 views.py views execute_script_result_analysis_fun 1607: 首页(顶部区域搜索框点击):PASS:[time_consuming:0.062872]{ response : 'resultCode: 0' }
INFO 2018-04-23 15:07:44,682 views.py views execute_script_result_analysis_fun 1607: 存储用户Session:PASS:[time_consuming:0.053397]{ response : 'resultCode: 0' }
INFO 2018-04-23 15:11:14,646 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-23 15:11:56,195 views.py views execute_script_result_analysis_fun 1607: 登录初始化:PASS:[time_consuming:0.127008]{ response : 'resultCode: 0' }
INFO 2018-04-23 15:11:56,568 views.py views execute_script_result_analysis_fun 1607: 首页(顶部区域搜索框点击):PASS:[time_consuming:0.122194]{ response : 'resultCode: 0' }
INFO 2018-04-23 15:11:56,917 views.py views execute_script_result_analysis_fun 1607: 存储用户Session:PASS:[time_consuming:0.063097]{ response : 'resultCode: 0' }
INFO 2018-04-23 15:26:05,861 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-23 15:26:56,906 views.py views execute_script_result_analysis_fun 1611: 实时获取tab标签发现（信息）-2018_4_20_18_23_32.py:PASS:[time_consuming:0.281509]{ response : 'resultCode: 0' }
INFO 2018-04-23 15:26:57,504 views.py views execute_script_result_analysis_fun 1611: 平台框架获取事件列表-2018_4_20_18_23_32.py:PASS:[time_consuming:0.060106]{ response : 'resultCode: 0' }
INFO 2018-04-23 15:26:57,849 views.py views execute_script_result_analysis_fun 1611: 更新绑定用户信息-2018_4_20_18_23_32.py:PASS:[time_consuming:0.072576]{ response : 'resultCode: 0' }
ERROR 2018-04-23 15:26:58,122 views.py views execute_script_result_analysis_fun 1647: 检查版本信息-2018_4_20_18_23_31.py:FAILED: error message [ 未获取脚本执行状态，脚本执行失败 ] Traceback (most recent call last):
  File "/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/检查版本信息-2018_4_20_18_23_31.py", line 17, in testDemo
    r = requests.post(self.protocol + domian + url, headers=headers, timeout=8)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 306, in prepare
    self.prepare_headers(headers)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 440, in prepare_headers
    check_header_validity(header)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/utils.py", line 872, in check_header_validity
    "bytes, not %s" % (name, value, type(value)))
InvalidHeader: Value for header {appId: 1} must be of type str or bytes, not <type 'int'>


INFO 2018-04-23 15:26:58,441 views.py views execute_script_result_analysis_fun 1611: 登录初始化-2018_4_20_18_23_32.py:PASS:[time_consuming:0.049697]{ response : 'resultCode: 0' }
INFO 2018-04-23 15:35:52,418 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-23 15:36:29,915 views.py views execute_script_result_analysis_fun 1614: 实时获取tab标签发现（信息）-2018_4_20_18_23_32.py:PASS:[time_consuming:0.211517]{ response : 'resultCode: 0' }
INFO 2018-04-23 15:36:30,622 views.py views execute_script_result_analysis_fun 1614: 平台框架获取事件列表-2018_4_20_18_23_32.py:PASS:[time_consuming:0.076996]{ response : 'resultCode: 0' }
INFO 2018-04-23 15:36:31,109 views.py views execute_script_result_analysis_fun 1614: 更新绑定用户信息-2018_4_20_18_23_32.py:PASS:[time_consuming:0.116196]{ response : 'resultCode: 0' }
ERROR 2018-04-23 15:36:31,412 views.py views execute_script_result_analysis_fun 1650: 检查版本信息-2018_4_20_18_23_31.py:FAILED: error message [ 未获取脚本执行状态，脚本执行失败 ] Traceback (most recent call last):
  File "/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/检查版本信息-2018_4_20_18_23_31.py", line 17, in testDemo
    r = requests.post(self.protocol + domian + url, headers=headers, timeout=8)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 306, in prepare
    self.prepare_headers(headers)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 440, in prepare_headers
    check_header_validity(header)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/utils.py", line 872, in check_header_validity
    "bytes, not %s" % (name, value, type(value)))
InvalidHeader: Value for header {appId: 1} must be of type str or bytes, not <type 'int'>


INFO 2018-04-23 15:36:31,720 views.py views execute_script_result_analysis_fun 1614: 登录初始化-2018_4_20_18_23_32.py:PASS:[time_consuming:0.054905]{ response : 'resultCode: 0' }
INFO 2018-04-23 15:41:12,636 views.py views execute_script_result_analysis_fun 1609: 实时获取tab标签发现（信息）-2018_4_20_18_23_32.py:PASS:[time_consuming:0.183191]{ response : 'resultCode: 0' }
INFO 2018-04-23 15:41:12,991 views.py views execute_script_result_analysis_fun 1609: 平台框架获取事件列表-2018_4_20_18_23_32.py:PASS:[time_consuming:0.069244]{ response : 'resultCode: 0' }
INFO 2018-04-23 15:41:13,280 views.py views execute_script_result_analysis_fun 1609: 更新绑定用户信息-2018_4_20_18_23_32.py:PASS:[time_consuming:0.059458]{ response : 'resultCode: 0' }
ERROR 2018-04-23 15:41:13,545 views.py views execute_script_result_analysis_fun 1645: 检查版本信息-2018_4_20_18_23_31.py:FAILED: error message [ 未获取脚本执行状态，脚本执行失败 ] Traceback (most recent call last):
  File "/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/检查版本信息-2018_4_20_18_23_31.py", line 17, in testDemo
    r = requests.post(self.protocol + domian + url, headers=headers, timeout=8)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 306, in prepare
    self.prepare_headers(headers)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 440, in prepare_headers
    check_header_validity(header)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/utils.py", line 872, in check_header_validity
    "bytes, not %s" % (name, value, type(value)))
InvalidHeader: Value for header {appId: 1} must be of type str or bytes, not <type 'int'>


INFO 2018-04-23 15:41:13,879 views.py views execute_script_result_analysis_fun 1609: 登录初始化-2018_4_20_18_23_32.py:PASS:[time_consuming:0.05115]{ response : 'resultCode: 0' }
INFO 2018-04-23 15:43:50,901 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-23 15:44:02,595 views.py views execute_script_result_analysis_fun 1612: 实时获取tab标签发现（信息）-2018_4_20_18_23_32.py:PASS:[time_consuming:0.185799]{ response : 'resultCode: 0' }
INFO 2018-04-23 15:44:03,031 views.py views execute_script_result_analysis_fun 1612: 平台框架获取事件列表-2018_4_20_18_23_32.py:PASS:[time_consuming:0.066269]{ response : 'resultCode: 0' }
INFO 2018-04-23 15:44:03,340 views.py views execute_script_result_analysis_fun 1612: 更新绑定用户信息-2018_4_20_18_23_32.py:PASS:[time_consuming:0.080177]{ response : 'resultCode: 0' }
ERROR 2018-04-23 15:44:03,634 views.py views execute_script_result_analysis_fun 1648: 检查版本信息-2018_4_20_18_23_31.py:FAILED: error message [ 未获取脚本执行状态，脚本执行失败 ] Traceback (most recent call last):
  File "/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/检查版本信息-2018_4_20_18_23_31.py", line 17, in testDemo
    r = requests.post(self.protocol + domian + url, headers=headers, timeout=8)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 306, in prepare
    self.prepare_headers(headers)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 440, in prepare_headers
    check_header_validity(header)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/utils.py", line 872, in check_header_validity
    "bytes, not %s" % (name, value, type(value)))
InvalidHeader: Value for header {appId: 1} must be of type str or bytes, not <type 'int'>


INFO 2018-04-23 15:44:03,942 views.py views execute_script_result_analysis_fun 1612: 登录初始化-2018_4_20_18_23_32.py:PASS:[time_consuming:0.05758]{ response : 'resultCode: 0' }
INFO 2018-04-23 16:00:08,293 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-23 16:00:30,938 views.py views execute_script_result_analysis_fun 1608: 实时获取tab标签发现（信息）-2018_4_20_18_23_32.py:PASS:[time_consuming:0.367051]{ response : 'resultCode: 0' }
INFO 2018-04-23 16:00:31,377 views.py views execute_script_result_analysis_fun 1608: 平台框架获取事件列表-2018_4_20_18_23_32.py:PASS:[time_consuming:0.068886]{ response : 'resultCode: 0' }
INFO 2018-04-23 16:00:31,744 views.py views execute_script_result_analysis_fun 1608: 更新绑定用户信息-2018_4_20_18_23_32.py:PASS:[time_consuming:0.067031]{ response : 'resultCode: 0' }
ERROR 2018-04-23 16:00:32,072 views.py views execute_script_result_analysis_fun 1644: 检查版本信息-2018_4_20_18_23_31.py:FAILED: error message [ 未获取脚本执行状态，脚本执行失败 ] Traceback (most recent call last):
  File "/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/检查版本信息-2018_4_20_18_23_31.py", line 17, in testDemo
    r = requests.post(self.protocol + domian + url, headers=headers, timeout=8)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 306, in prepare
    self.prepare_headers(headers)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 440, in prepare_headers
    check_header_validity(header)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/utils.py", line 872, in check_header_validity
    "bytes, not %s" % (name, value, type(value)))
InvalidHeader: Value for header {appId: 1} must be of type str or bytes, not <type 'int'>


INFO 2018-04-23 16:00:32,458 views.py views execute_script_result_analysis_fun 1608: 登录初始化-2018_4_20_18_23_32.py:PASS:[time_consuming:0.057888]{ response : 'resultCode: 0' }
INFO 2018-04-23 16:02:02,450 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-23 16:02:12,757 views.py views execute_script_result_analysis_fun 1608: 实时获取tab标签发现（信息）-2018_4_20_18_23_32.py:PASS:[time_consuming:0.285501]{ response : 'resultCode: 0' }
INFO 2018-04-23 16:02:13,258 views.py views execute_script_result_analysis_fun 1608: 平台框架获取事件列表-2018_4_20_18_23_32.py:PASS:[time_consuming:0.064506]{ response : 'resultCode: 0' }
INFO 2018-04-23 16:02:13,590 views.py views execute_script_result_analysis_fun 1608: 更新绑定用户信息-2018_4_20_18_23_32.py:PASS:[time_consuming:0.069913]{ response : 'resultCode: 0' }
ERROR 2018-04-23 16:02:13,867 views.py views execute_script_result_analysis_fun 1644: 检查版本信息-2018_4_20_18_23_31.py:FAILED: error message [ 未获取脚本执行状态，脚本执行失败 ] Traceback (most recent call last):
  File "/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/检查版本信息-2018_4_20_18_23_31.py", line 17, in testDemo
    r = requests.post(self.protocol + domian + url, headers=headers, timeout=8)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 306, in prepare
    self.prepare_headers(headers)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 440, in prepare_headers
    check_header_validity(header)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/utils.py", line 872, in check_header_validity
    "bytes, not %s" % (name, value, type(value)))
InvalidHeader: Value for header {appId: 1} must be of type str or bytes, not <type 'int'>


INFO 2018-04-23 16:02:14,197 views.py views execute_script_result_analysis_fun 1608: 登录初始化-2018_4_20_18_23_32.py:PASS:[time_consuming:0.061736]{ response : 'resultCode: 0' }
INFO 2018-04-23 16:03:29,649 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-23 16:03:44,725 views.py views execute_script_result_analysis_fun 1608: 实时获取tab标签发现（信息）-2018_4_20_18_23_32.py:PASS:[time_consuming:0.186028]{ response : 'resultCode: 0' }
INFO 2018-04-23 16:03:45,141 views.py views execute_script_result_analysis_fun 1608: 平台框架获取事件列表-2018_4_20_18_23_32.py:PASS:[time_consuming:0.06861]{ response : 'resultCode: 0' }
INFO 2018-04-23 16:03:45,477 views.py views execute_script_result_analysis_fun 1608: 更新绑定用户信息-2018_4_20_18_23_32.py:PASS:[time_consuming:0.060119]{ response : 'resultCode: 0' }
ERROR 2018-04-23 16:03:45,749 views.py views execute_script_result_analysis_fun 1644: 检查版本信息-2018_4_20_18_23_31.py:FAILED: error message [ 未获取脚本执行状态，脚本执行失败 ] Traceback (most recent call last):
  File "/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/检查版本信息-2018_4_20_18_23_31.py", line 17, in testDemo
    r = requests.post(self.protocol + domian + url, headers=headers, timeout=8)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 306, in prepare
    self.prepare_headers(headers)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 440, in prepare_headers
    check_header_validity(header)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/utils.py", line 872, in check_header_validity
    "bytes, not %s" % (name, value, type(value)))
InvalidHeader: Value for header {appId: 1} must be of type str or bytes, not <type 'int'>


INFO 2018-04-23 16:03:46,039 views.py views execute_script_result_analysis_fun 1608: 登录初始化-2018_4_20_18_23_32.py:PASS:[time_consuming:0.052715]{ response : 'resultCode: 0' }
INFO 2018-04-23 16:06:35,896 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-23 16:06:54,793 views.py views execute_script_result_analysis_fun 1608: 登录初始化:PASS:[time_consuming:0.098962]{ response : 'resultCode: 0' }
INFO 2018-04-23 16:06:55,218 views.py views execute_script_result_analysis_fun 1608: 首页(顶部区域搜索框点击):PASS:[time_consuming:0.067292]{ response : 'resultCode: 0' }
INFO 2018-04-23 16:06:55,553 views.py views execute_script_result_analysis_fun 1608: 存储用户Session:PASS:[time_consuming:0.056833]{ response : 'resultCode: 0' }
INFO 2018-04-23 16:53:01,701 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-23 16:53:43,032 views.py views project_manage 87: 进入项目中心-->项目管理页面
INFO 2018-04-23 16:53:43,078 views.py views project_manage 87: 进入项目中心-->项目管理页面
INFO 2018-04-23 16:53:43,216 views.py views Read_all_project 106: 查询所有项目
INFO 2018-04-23 16:53:43,391 views.py views Read_all_project 106: 查询所有项目
INFO 2018-04-23 16:53:45,789 views.py views income_project 142: gonglp进入项目[TBS_USER_20180328]
INFO 2018-04-23 16:53:47,302 views.py views workon_tabs_api 386: gonglp进入接口管理页面 [TBS_USER_20180328]
INFO 2018-04-23 16:54:31,922 views.py views execute_script_result_analysis_fun 1607: 登录初始化:PASS:[time_consuming:0.188552]{ response : 'resultCode: 0' }
INFO 2018-04-23 16:54:32,404 views.py views execute_script_result_analysis_fun 1607: 首页(顶部区域搜索框点击):PASS:[time_consuming:0.096103]{ response : 'resultCode: 0' }
INFO 2018-04-23 16:54:32,744 views.py views execute_script_result_analysis_fun 1607: 存储用户Session:PASS:[time_consuming:0.06142]{ response : 'resultCode: 0' }
INFO 2018-04-23 16:55:58,215 views.py views execute_script_result_analysis_fun 1607: 实时获取tab标签发现（信息）-2018_4_23_16_14_40.py:PASS:[time_consuming:0.221985]{ response : 'resultCode: 0' }
INFO 2018-04-23 16:55:58,819 views.py views execute_script_result_analysis_fun 1607: 平台框架获取事件列表-2018_4_23_16_14_40.py:PASS:[time_consuming:0.065797]{ response : 'resultCode: 0' }
INFO 2018-04-23 16:55:59,155 views.py views execute_script_result_analysis_fun 1607: 更新绑定用户信息-2018_4_23_16_14_40.py:PASS:[time_consuming:0.064668]{ response : 'resultCode: 0' }
ERROR 2018-04-23 16:55:59,506 views.py views execute_script_result_analysis_fun 1643: 检查版本信息-2018_4_23_16_14_40.py:FAILED: error message [ 未获取脚本执行状态，脚本执行失败 ] Traceback (most recent call last):
  File "/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/检查版本信息-2018_4_23_16_14_40.py", line 17, in testDemo
    r = requests.post(self.protocol + domian + url, headers=headers, timeout=8)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 306, in prepare
    self.prepare_headers(headers)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 440, in prepare_headers
    check_header_validity(header)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/utils.py", line 872, in check_header_validity
    "bytes, not %s" % (name, value, type(value)))
InvalidHeader: Value for header {appId: 1} must be of type str or bytes, not <type 'int'>


INFO 2018-04-23 16:55:59,799 views.py views execute_script_result_analysis_fun 1607: 登录初始化-2018_4_23_16_14_40.py:PASS:[time_consuming:0.050433]{ response : 'resultCode: 0' }
INFO 2018-04-23 17:01:00,782 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-23 17:01:20,095 views.py views execute_script_result_analysis_fun 1607: 登录初始化:PASS:[time_consuming:0.177954]{ response : 'resultCode: 0' }
INFO 2018-04-23 17:01:20,413 views.py views execute_script_result_analysis_fun 1607: 首页(顶部区域搜索框点击):PASS:[time_consuming:0.060053]{ response : 'resultCode: 0' }
INFO 2018-04-23 17:01:20,668 views.py views execute_script_result_analysis_fun 1607: 存储用户Session:PASS:[time_consuming:0.055762]{ response : 'resultCode: 0' }
ERROR 2018-04-23 17:02:14,605 views.py views execute_script_result_analysis_fun 1643: 检查版本信息:FAILED: error message [ 未获取脚本执行状态，脚本执行失败 ] Traceback (most recent call last):
  File "/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/检查版本信息-2018_4_23_16_14_40.py", line 17, in testDemo
    r = requests.post(self.protocol + domian + url, headers=headers, timeout=8)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 306, in prepare
    self.prepare_headers(headers)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 440, in prepare_headers
    check_header_validity(header)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/utils.py", line 872, in check_header_validity
    "bytes, not %s" % (name, value, type(value)))
InvalidHeader: Value for header {appId: 1} must be of type str or bytes, not <type 'int'>


INFO 2018-04-23 17:02:15,039 views.py views execute_script_result_analysis_fun 1607: 实时获取tab标签发现（信息）:PASS:[time_consuming:0.187188]{ response : 'resultCode: 0' }
INFO 2018-04-23 17:02:15,532 views.py views execute_script_result_analysis_fun 1607: 平台框架获取事件列表:PASS:[time_consuming:0.079084]{ response : 'resultCode: 0' }
INFO 2018-04-23 17:02:15,826 views.py views execute_script_result_analysis_fun 1607: 更新绑定用户信息:PASS:[time_consuming:0.058083]{ response : 'resultCode: 0' }
INFO 2018-04-23 17:26:31,142 views.py views login_handle 53: [gonglp] 登录成功
INFO 2018-04-23 17:27:25,459 views.py views project_manage 87: 进入项目中心-->项目管理页面
INFO 2018-04-23 17:27:25,482 views.py views project_manage 87: 进入项目中心-->项目管理页面
INFO 2018-04-23 17:27:25,624 views.py views Read_all_project 106: 查询所有项目
INFO 2018-04-23 17:27:25,812 views.py views Read_all_project 106: 查询所有项目
INFO 2018-04-23 17:27:27,419 views.py views income_project 142: gonglp进入项目[TBS_USER_20180328]
INFO 2018-04-23 17:27:29,223 views.py views workon_tabs_api 386: gonglp进入接口管理页面 [TBS_USER_20180328]
ERROR 2018-04-23 17:28:06,588 views.py views execute_huigui_script 1787: 回归测试执行失败 [Caused by :兔博士用户端 还有冒烟用例未生成测试脚本，请补充测试脚本！] 请检查以下case_id [u'TBS_DL_GetEventList']
ERROR 2018-04-23 17:30:17,313 views.py views execute_script_result_analysis_fun 1643: 检查版本信息:FAILED: error message [ 未获取脚本执行状态，脚本执行失败 ] Traceback (most recent call last):
  File "/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/检查版本信息-2018_4_23_16_14_40.py", line 17, in testDemo
    r = requests.post(self.protocol + domian + url, headers=headers, timeout=8)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 306, in prepare
    self.prepare_headers(headers)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 440, in prepare_headers
    check_header_validity(header)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/utils.py", line 872, in check_header_validity
    "bytes, not %s" % (name, value, type(value)))
InvalidHeader: Value for header {appId: 1} must be of type str or bytes, not <type 'int'>


INFO 2018-04-23 17:30:17,901 views.py views execute_script_result_analysis_fun 1607: 实时获取tab标签发现（信息）:PASS:[time_consuming:0.256209]{ response : 'resultCode: 0' }
INFO 2018-04-23 17:30:18,407 views.py views execute_script_result_analysis_fun 1607: 平台框架获取事件列表:PASS:[time_consuming:0.065034]{ response : 'resultCode: 0' }
INFO 2018-04-23 17:30:18,712 views.py views execute_script_result_analysis_fun 1607: 更新绑定用户信息:PASS:[time_consuming:0.060251]{ response : 'resultCode: 0' }
INFO 2018-04-23 17:31:03,232 views.py views project_manage 87: 进入项目中心-->项目管理页面
INFO 2018-04-23 17:31:03,367 views.py views Read_all_project 106: 查询所有项目
INFO 2018-04-23 17:33:20,047 views.py views project_manage 87: 进入项目中心-->项目管理页面
INFO 2018-04-23 17:33:20,201 views.py views Read_all_project 106: 查询所有项目
INFO 2018-04-23 17:33:21,937 views.py views project_manage 87: 进入项目中心-->项目管理页面
INFO 2018-04-23 17:33:22,047 views.py views Read_all_project 106: 查询所有项目
INFO 2018-04-23 17:33:22,499 views.py views project_manage 87: 进入项目中心-->项目管理页面
INFO 2018-04-23 17:33:22,612 views.py views Read_all_project 106: 查询所有项目
INFO 2018-04-23 17:33:22,865 views.py views project_manage 87: 进入项目中心-->项目管理页面
INFO 2018-04-23 17:33:22,977 views.py views Read_all_project 106: 查询所有项目
INFO 2018-04-23 17:38:30,829 views.py views API_start 463: gonglp添加API用例 [测试] 属于项目：[TBS_USER_20180328]
INFO 2018-04-23 17:41:11,685 views.py views project_manage 87: 进入项目中心-->项目管理页面
INFO 2018-04-23 17:41:11,884 views.py views Read_all_project 106: 查询所有项目
INFO 2018-04-23 17:41:13,002 views.py views income_project 142: 进入项目[TBS_USER_20180328]
INFO 2018-04-23 17:41:14,236 views.py views project_manage 87: 进入项目中心-->项目管理页面
INFO 2018-04-23 17:41:14,354 views.py views Read_all_project 106: 查询所有项目
INFO 2018-04-23 17:41:15,695 views.py views workon_tabs_api 386: 进入接口管理页面 [TBS_USER_20180328]
INFO 2018-04-23 17:41:37,339 views.py views project_manage 87: 进入项目中心-->项目管理页面
INFO 2018-04-23 17:41:37,564 views.py views Read_all_project 106: 查询所有项目
INFO 2018-04-23 17:41:40,889 views.py views income_project 142: 进入项目[TBS_USER_20180328]
INFO 2018-04-23 17:41:48,571 views.py views workon_tabs_api 386: 进入接口管理页面 [TBS_USER_20180328]
INFO 2018-04-23 17:42:46,680 views.py views project_manage 87: 进入项目中心-->项目管理页面
INFO 2018-04-23 17:42:46,850 views.py views Read_all_project 106: 查询所有项目
INFO 2018-04-23 17:42:47,551 views.py views project_manage 87: 进入项目中心-->项目管理页面
INFO 2018-04-23 17:42:47,673 views.py views Read_all_project 106: 查询所有项目
INFO 2018-04-23 17:42:48,054 views.py views income_project 142: 进入项目[TBS_USER_20180328]
INFO 2018-04-23 17:42:48,809 views.py views project_manage 87: 进入项目中心-->项目管理页面
INFO 2018-04-23 17:42:48,930 views.py views Read_all_project 106: 查询所有项目
INFO 2018-04-23 17:42:50,181 views.py views workon_tabs_api 386: 进入接口管理页面 [TBS_USER_20180328]
INFO 2018-04-23 17:42:57,423 views.py views income_project 142: 进入项目[TBS_USER_20180328]
INFO 2018-04-23 17:42:59,239 views.py views project_manage 87: 进入项目中心-->项目管理页面
INFO 2018-04-23 17:42:59,478 views.py views Read_all_project 106: 查询所有项目
INFO 2018-04-23 17:43:03,982 views.py views workon_tabs_api 386: 进入接口管理页面 [TBS_USER_20180328]
INFO 2018-04-23 17:45:47,538 views.py views income_project 142: 进入项目[TBS_USER_20180328]
INFO 2018-04-23 17:45:48,441 views.py views project_manage 87: 进入项目中心-->项目管理页面
INFO 2018-04-23 17:45:48,677 views.py views Read_all_project 106: 查询所有项目
INFO 2018-04-23 17:45:49,876 views.py views workon_tabs_api 386: 进入接口管理页面 [TBS_USER_20180328]
INFO 2018-04-23 17:49:16,779 views.py views income_project 142: 进入项目[TBS_USER_20180328]
INFO 2018-04-23 17:49:22,032 views.py views project_manage 87: 进入项目中心-->项目管理页面
INFO 2018-04-23 17:49:22,148 views.py views Read_all_project 106: 查询所有项目
INFO 2018-04-23 17:49:26,210 views.py views project_manage 87: 进入项目中心-->项目管理页面
INFO 2018-04-23 17:49:26,219 views.py views project_manage 87: 进入项目中心-->项目管理页面
INFO 2018-04-23 17:49:26,357 views.py views Read_all_project 106: 查询所有项目
INFO 2018-04-23 17:49:28,348 views.py views income_project 142: gonglp进入项目[TBS_USER_20180328]
INFO 2018-04-23 17:49:31,348 views.py views workon_tabs_api 386: gonglp进入接口管理页面 [TBS_USER_20180328]
INFO 2018-04-23 17:50:34,043 views.py views API_start 474: gonglp添加API用例 [测试] 属于项目：[TBS_USER_20180328]
INFO 2018-04-23 17:51:38,980 views.py views income_project 142: 进入项目[TBS_USER_20180328]
INFO 2018-04-23 17:51:39,650 views.py views project_manage 87: 进入项目中心-->项目管理页面
INFO 2018-04-23 17:51:39,777 views.py views Read_all_project 106: 查询所有项目
INFO 2018-04-23 17:51:45,177 views.py views income_project 142: gonglp进入项目[TBS_USER_20180328]
INFO 2018-04-23 17:51:57,165 views.py views workon_tabs_api 386: gonglp进入接口管理页面 [TBS_USER_20180328]
INFO 2018-04-23 17:54:13,907 views.py views execute_script_result_analysis_fun 1638: 登录初始化:PASS:[time_consuming:0.130529]{ response : 'resultCode: 0' }
INFO 2018-04-23 17:54:14,342 views.py views execute_script_result_analysis_fun 1638: 首页(顶部区域搜索框点击):PASS:[time_consuming:0.06934]{ response : 'resultCode: 0' }
INFO 2018-04-23 17:54:14,640 views.py views execute_script_result_analysis_fun 1638: 存储用户Session:PASS:[time_consuming:0.059427]{ response : 'resultCode: 0' }
ERROR 2018-04-23 17:55:04,798 views.py views execute_script_result_analysis_fun 1674: 检查版本信息:FAILED: error message [ 未获取脚本执行状态，脚本执行失败 ] Traceback (most recent call last):
  File "/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/检查版本信息-2018_4_23_16_14_40.py", line 17, in testDemo
    r = requests.post(self.protocol + domian + url, headers=headers, timeout=8)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 306, in prepare
    self.prepare_headers(headers)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 440, in prepare_headers
    check_header_validity(header)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/utils.py", line 872, in check_header_validity
    "bytes, not %s" % (name, value, type(value)))
InvalidHeader: Value for header {appId: 1} must be of type str or bytes, not <type 'int'>


INFO 2018-04-23 17:55:05,510 views.py views execute_script_result_analysis_fun 1638: 实时获取tab标签发现（信息）:PASS:[time_consuming:0.34476]{ response : 'resultCode: 0' }
INFO 2018-04-23 17:55:05,908 views.py views execute_script_result_analysis_fun 1638: 平台框架获取事件列表:PASS:[time_consuming:0.067194]{ response : 'resultCode: 0' }
INFO 2018-04-23 17:55:06,363 views.py views execute_script_result_analysis_fun 1638: 更新绑定用户信息:PASS:[time_consuming:0.065386]{ response : 'resultCode: 0' }
